server:
  port: 8081
  servlet:
    context-path: /security
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: kw002
    password: 123456
    url: jdbc:mysql://192.168.0.107:3306/book?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
#sql日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
